name: develop workflow

on:
  push:
    branches:
      - develop

jobs:
  call-workflow-frontend-docker:
    uses: ./.github/workflows/frontend-docker.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  call-workflow-backend-docker:
    needs: call-workflow-frontend-docker
    uses: ./.github/workflows/backend-docker.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}